# model

model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct


### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: primevul_train_paired_output
template: qwen
# cutoff_len: 4096 max
cutoff_len: 2048
max_samples: 28302
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwn2.5_vul/full/sft_6
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000
